### ISSUE TITLE
ReferenceError: vendor_root_cert is not defined at pg_certificates page

### ISSUE THREAD

**Issue by dnoliver** [google/tpm-js#4]
To reproduce: navigate to https://google.github.io/tpm-js/#pg_certificates and click the second Run button. 

Output:

```
ReferenceError: vendor_root_cert is not defined
    at eval (eval at <anonymous> (https://google.github.io/tpm-js/js/main.js:291:44), <anonymous>:20:21)
    at https://google.github.io/tpm-js/js/main.js:291:44
    at l (https://code.jquery.com/jquery-3.3.1.min.js:2:29375)
    at c (https://code.jquery.com/jquery-3.3.1.min.js:2:29677)
```

**Comment by dnoliver** [comment]
An assertion fails as well in the next run button, 

```
abort("Assertion failed: NvReadPublic failed") at Error
    at jsStackTrace (https://google.github.io/tpm-js/wasm/bindings.js:1021:13)
    at stackTrace (https://google.github.io/tpm-js/wasm/bindings.js:1038:12)
    at abort (https://google.github.io/tpm-js/wasm/bindings.js:8765:44)
    at assert (https://google.github.io/tpm-js/wasm/bindings.js:405:5)
    at eval (eval at <anonymous> (https://google.github.io/tpm-js/js/main.js:291:44), <anonymous>:13:3)
    at https://google.github.io/tpm-js/js/main.js:291:44
    at l (https://code.jquery.com/jquery-3.3.1.min.js:2:29375)
    at c (https://code.jquery.com/jquery-3.3.1.min.js:2:29677)
```

**Comment by cfircohen** [comment]
Thanks for reporting the issue. You'll notice that the first script window defines "vendor_root_cert", so if you execute the codelab sessions in order, you won't get these errors. 
I tried to avoid dependencies between codelab windows as much as I could, but #pg_certificates has so much content in it, I had to break it up to multiple, linearly dependent, windows.

**Comment by dnoliver** [comment]
Regardless of those stack traces, the examples are great an easy to follow! It could be much more complex to understand if it was all a single window  with all the commands, agree on that :)

**Comment by cfircohen** [comment]
Thanks for your notes.
